name: PHP Composer

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Composer
      run: |
        pwd
        composer --version
        composer global require hirak/prestissimo -n -q
        composer validate
        composer install -n -q --prefer-dist
        echo 'export PATH=$GITHUB_WORKSPACE/vendor/bin:$PATH' >> $BASH_ENV
        echo '$BASH_ENV'
        source $HOME/.bashrc
        drush --version

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
