name: Drupal Behat

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: circleci/php:7.3-apache-node-browsers

    services:
      mariadb:
        image: circleci/mariadb:latest
        ports:
          - 33306:3306

    steps:
    - uses: actions/checkout@v2

    - name: Composer
      run: |
        php -v
        whoami
        pwd
        composer --version
        composer validate
        composer global require hirak/prestissimo -n --prefer-dist
        composer install -n --prefer-dist
        echo "export PATH=$PATH:$GITHUB_WORKSPACE/vendor/bin" >> ~/.bash_profile
