name: PHP Composer

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Composer
      run: |
        composer --version
        composer validate
        composer global require hirak/prestissimo -n --prefer-dist
        composer install -n --prefer-dist
        echo "export PATH=$PATH:$GITHUB_WORKSPACE/vendor/bin" >> ~/.bash_profile

    - name: Drupal
      shell: bash -l {0}
      run: |
        mysql --defaults-extra-file=.github/workflows/my.cnf -e "create database if not exists github_actions"
        cp .github/workflows/settings.local.php web/sites/default/settings.local.php
        drush site:install --site-name "Hello World"

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
